<a href="https://colab.research.google.com/github/runyasimre94/meLearn/blob/main/meNumpyTut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Array vs List


In [ ]:
import numpy as np

In [ ]:
L = [1, 2, 3]

In [ ]:
A = np.array([1, 2, 3])

In [ ]:
for i in L:
  print(i)

1
2
3


In [ ]:
for i in A:
  print(i)

1
2
3


In [ ]:
L.append(4)

In [ ]:
L

[1, 2, 3, 4]

In [ ]:
A.append(4)

AttributeError: ignored

In [ ]:
A + np.array([4]) # now np makes broadcasting


array([5, 6, 7])

In [ ]:
L +[5]

[1, 2, 3, 4, 5]

In [ ]:
A + np.array([4, 5, 6])

array([5, 7, 9])

In [ ]:
A + np.array([4, 5])

ValueError: ignored

In [ ]:
2 * A

array([2, 4, 6])

In [ ]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L + L

In [ ]:
L2 = []
for e in L:
  L2.append(e + 2)

In [ ]:
L2

[3, 4, 5, 6]

In [ ]:
#we can also do it with list comprehension
L3 = [e + 2 for  e in L]

In [ ]:
L3

[3, 4, 5, 6]

In [ ]:
L2**2

TypeError: ignored

In [ ]:
L2 =  []
L2 = [e * e for e in L]

In [ ]:
L2

[1, 4, 9, 16]

In [ ]:
A**2

array([1, 4, 9])

In [ ]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

# DOT PRODUCT

The zip() function returns a zip object, which is an iterator of tuples where the first item in each passed iterator is paired together, and then the second item in each passed iterator are paired together etc.

If the passed iterators have different lengths, the iterator with the least items decides the length of the new iterator.


In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])

In [ ]:
dot = 0
for e,f in zip(a, b):
  dot += e * f

print(dot)

11


In [ ]:
c = ("John", "Charles", "Mike")
d = ("Jenny", "Christy", "Monica", "Isma", "Ermis")

x = zip(c, d)
for i in x:
  print(i)

('John', 'Jenny')
('Charles', 'Christy')
('Mike', 'Monica')


In [ ]:
dot = 0
for e in range(len(a)):
  dot += a[e] * b[e]

print(dot)

11


In [ ]:
a * b

array([3, 8])

In [ ]:
np.sum(a * b)

11

In [ ]:
(a * b).sum()

11

In [ ]:
np.dot(a, b)

11

In [ ]:
a.dot(b)

11

In [ ]:
a @ b

11

In [ ]:
maga = np.sqrt((a * a).sum())

In [ ]:
maga

2.23606797749979

In [ ]:
np.linalg.norm(a)

2.23606797749979

In [ ]:
cosangle = (a.dot(b)) /(np.linalg.norm(a) * np.linalg.norm(b))

In [ ]:
cosangle

0.9838699100999074

In [ ]:
angle = np.arccos(cosangle)

In [ ]:
angle

0.17985349979247847

In [ ]:
angle_in_degree = np.degrees(angle)

In [ ]:
angle_in_degree

10.304846468766044